# Generated by Django 4.2.3 on 2023-12-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job_details_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='applied_job',
            fields=[
                ('username', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('job_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='job_details',
            name='company_logo',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='media/'),
        ),
    ]
