# Generated by Django 4.2.3 on 2023-12-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_delete_applied_job_job_apllicaions_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_apllicaions',
            name='DOB',
            field=models.DateField(default='2003-09-17', max_length=15),
        ),
    ]
