# Generated by Django 4.2.3 on 2023-12-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_alter_job_apllicaions_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_apllicaions',
            name='DOB',
            field=models.CharField(default='2003-09-17', max_length=15),
        ),
    ]
