# Generated by Django 4.2.3 on 2023-12-16 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_alter_job_apllicaions_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_apllicaions',
            name='DOB',
        ),
    ]
