# Generated by Django 4.2.3 on 2023-12-16 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_remove_job_apllicaions_dob'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='job_apllicaions',
            new_name='job_apllicaion',
        ),
    ]
