# Generated by Django 4.2.3 on 2023-12-16 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_job_apllicaions_delete_job_apllicaion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='job_apllicaions',
        ),
    ]
