# Generated by Django 4.2.3 on 2023-12-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_job_apllicaions_address_job_apllicaions_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='hi', max_length=90)),
            ],
        ),
    ]
