# Generated by Django 4.2.3 on 2023-12-16 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_job_details_company_logo'),
        ('job', '0020_delete_stat_job_apllicaions_address_and_more'),
    ]

    operations = [
    ]
