# Generated by Django 4.2.3 on 2023-12-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0021_merge_20231216_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_apllicaions',
            name='DOB',
            field=models.CharField(default='today', max_length=20),
        ),
    ]
