# Generated by Django 4.2.3 on 2023-12-16 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0022_job_apllicaions_dob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='job_apllicaions',
        ),
    ]
