# Generated by Django 4.2.3 on 2023-12-16 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_applied_job_alter_job_details_company_logo'),
        ('job', '0023_delete_job_apllicaions'),
    ]

    operations = [
    ]
